<template>
  <div>
    <v-avatar size="30">
      <img
        src="@/assets/images/propil.png"
        alt="John"
      >
    </v-avatar>
    <v-btn
      icon
    >
      <v-icon>mdi-bell</v-icon>
    </v-btn>
    <v-btn
      icon
    >
      <v-icon>mdi-location-exit</v-icon>
    </v-btn>
  </div>
</template>
